# Generated by Django 6.0.3 on 2026-03-16 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('style', models.CharField(choices=[('mediterranean', 'Méditerranéen'), ('japanese', 'Japonais'), ('tropical', 'Tropical'), ('contemporary', 'Contemporain'), ('countryside', 'Champêtre')], max_length=20, verbose_name='style')),
                ('status', models.CharField(choices=[('generating', 'Génération en cours'), ('draft', 'Brouillon'), ('validated', 'Validé'), ('error', 'Erreur')], default='generating', max_length=20, verbose_name='statut')),
                ('canvas_width_m', models.FloatField(blank=True, null=True, verbose_name='largeur canvas (m)')),
                ('canvas_height_m', models.FloatField(blank=True, null=True, verbose_name='hauteur canvas (m)')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL miniature')),
                ('export_2d_url', models.URLField(blank=True, verbose_name='URL export 2D')),
                ('export_3d_url', models.URLField(blank=True, verbose_name='URL export 3D')),
                ('generation_params', models.JSONField(blank=True, default=dict, help_text="Paramètres envoyés à l'IA", verbose_name='paramètres de génération')),
                ('ai_model_used', models.CharField(blank=True, max_length=50, verbose_name='modèle IA utilisé')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='généré le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'design',
                'verbose_name_plural': 'designs',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('plant', 'Plante'), ('path', 'Allée'), ('terrace', 'Terrasse'), ('wall', 'Mur'), ('water_feature', "Point d'eau"), ('furniture', 'Mobilier'), ('lighting', 'Éclairage'), ('fence', 'Clôture'), ('lawn', 'Pelouse'), ('mulch', 'Paillage')], max_length=20, verbose_name="type d'élément")),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='libellé')),
                ('position', models.TextField(help_text="Position centrale de l'élément (GeoJSON Point)", verbose_name='position')),
                ('geometry', models.TextField(blank=True, help_text="Emprise géométrique de l'élément (GeoJSON Polygon)", null=True, verbose_name='emprise au sol')),
                ('rotation_deg', models.FloatField(default=0, verbose_name='rotation (degrés)')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantité')),
                ('spacing_cm', models.IntegerField(blank=True, null=True, verbose_name='espacement (cm)')),
                ('phase', models.IntegerField(default=1, help_text='Phase de réalisation (1, 2 ou 3)', verbose_name='phase')),
                ('is_locked', models.BooleanField(default=False, help_text='Élément verrouillé contre modification', verbose_name='verrouillé')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('added_by', models.CharField(choices=[('ai', 'IA'), ('user', 'Utilisateur')], default='ai', max_length=10, verbose_name='ajouté par')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='designs.design', verbose_name='design')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_uses', to='plants.plant', verbose_name='plante')),
            ],
            options={
                'verbose_name': 'élément de design',
                'verbose_name_plural': 'éléments de design',
                'indexes': [models.Index(fields=['design', 'element_type'], name='designs_des_design__f268ef_idx'), models.Index(fields=['design', 'phase'], name='designs_des_design__0d17c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemporalSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horizon', models.CharField(choices=[('m3', '3 mois'), ('m6', '6 mois'), ('m12', '12 mois'), ('m24', '24 mois')], max_length=10, verbose_name='horizon temporel')),
                ('season', models.CharField(choices=[('spring', 'Printemps'), ('summer', 'Été'), ('autumn', 'Automne'), ('winter', 'Hiver')], max_length=20, verbose_name='saison')),
                ('render_url', models.URLField(blank=True, verbose_name='URL du rendu')),
                ('video_url', models.URLField(blank=True, help_text='Plan Pro seulement', verbose_name='URL de la vidéo')),
                ('density_alerts', models.JSONField(blank=True, default=list, help_text='Liste des conflits végétaux détectés', verbose_name='alertes de densité')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='généré le')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_simulations', to='designs.design', verbose_name='design')),
            ],
            options={
                'verbose_name': 'simulation temporelle',
                'verbose_name_plural': 'simulations temporelles',
                'unique_together': {('design', 'horizon', 'season')},
            },
        ),
    ]
