# Generated by Django 6.0.3 on 2026-03-18 21:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGNUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Endpoint IGN appelé', max_length=100)),
                ('parcel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('response_status', models.IntegerField(help_text='Code de réponse HTTP')),
                ('response_time_ms', models.IntegerField(help_text='Temps de réponse en ms')),
                ('success', models.BooleanField(help_text="Succès de l'appel")),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log utilisation IGN',
                'verbose_name_plural': 'Logs utilisation IGN',
                'indexes': [models.Index(fields=['created_at'], name='geography_i_created_73392f_idx'), models.Index(fields=['endpoint'], name='geography_i_endpoin_e64888_idx'), models.Index(fields=['success'], name='geography_i_success_442c9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParcelEnrichment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_id', models.CharField(help_text='ID parcelle cadastrale', max_length=50, unique=True)),
                ('elevation_min', models.FloatField(blank=True, help_text='Altitude min (m) - IGN RGE ALTI', null=True)),
                ('elevation_max', models.FloatField(blank=True, help_text='Altitude max (m) - IGN RGE ALTI', null=True)),
                ('elevation_average', models.FloatField(blank=True, help_text='Altitude moyenne (m)', null=True)),
                ('elevation_profile', models.JSONField(default=list, help_text='Profil altimétrique détaillé')),
                ('slope_analysis', models.JSONField(default=dict, help_text='Analyse des pentes')),
                ('land_cover_data', models.JSONField(default=dict, help_text='OCS GE - occupation détaillée')),
                ('vegetation_cover_pct', models.FloatField(blank=True, help_text='% couverture végétale', null=True)),
                ('artificial_cover_pct', models.FloatField(blank=True, help_text='% surfaces artificialisées', null=True)),
                ('water_cover_pct', models.FloatField(blank=True, help_text='% surfaces en eau', null=True)),
                ('agricultural_cover_pct', models.FloatField(blank=True, help_text='% surfaces agricoles', null=True)),
                ('address_normalized', models.CharField(blank=True, help_text='Adresse IGN normalisée', max_length=255, null=True)),
                ('insee_code', models.CharField(blank=True, help_text='Code INSEE commune', max_length=5, null=True)),
                ('department', models.CharField(blank=True, help_text='Département', max_length=3, null=True)),
                ('region', models.CharField(blank=True, help_text='Région', max_length=2, null=True)),
                ('quality_score', models.FloatField(blank=True, help_text='Score qualité géocodage (0-1)', null=True)),
                ('distance_to_water', models.FloatField(blank=True, help_text="Distance cours d'eau (m)", null=True)),
                ('distance_to_road', models.FloatField(blank=True, help_text='Distance route principale (m)', null=True)),
                ('urban_density', models.CharField(blank=True, choices=[('sparse', 'Faible'), ('moderate', 'Modérée'), ('dense', 'Dense'), ('very_dense', 'Très dense')], help_text='Densité urbaine', max_length=20, null=True)),
                ('climate_zone_ign', models.CharField(blank=True, help_text='Zone climatique IGN', max_length=50, null=True)),
                ('enriched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ign_data_version', models.CharField(default='2024.1', help_text='Version données IGN', max_length=20)),
                ('cache_expires_at', models.DateTimeField(help_text='Expiration cache IGN (24h)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'Traitement en cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si échec", null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Nombre de tentatives')),
            ],
            options={
                'verbose_name': 'Enrichissement parcelle',
                'verbose_name_plural': 'Enrichissements parcelles',
                'indexes': [models.Index(fields=['parcel_id'], name='geography_p_parcel__df206a_idx'), models.Index(fields=['status'], name='geography_p_status_12ef30_idx'), models.Index(fields=['cache_expires_at'], name='geography_p_cache_e_83f76c_idx')],
            },
        ),
    ]
