# Generated by Django 6.0.3 on 2026-03-16 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_common_fr', models.CharField(max_length=200, verbose_name='nom commun français')),
                ('name_latin', models.CharField(max_length=200, verbose_name='nom latin')),
                ('type', models.CharField(choices=[('tree', 'Arbre'), ('shrub', 'Arbuste'), ('perennial', 'Vivace'), ('annual', 'Annuelle'), ('grass', 'Graminée'), ('groundcover', 'Couvre-sol'), ('climber', 'Grimpante'), ('aquatic', 'Aquatique'), ('bulb', 'Bulbeuse')], max_length=20, verbose_name='type')),
                ('height_adult_min_cm', models.IntegerField(blank=True, null=True, verbose_name='hauteur adulte min (cm)')),
                ('height_adult_max_cm', models.IntegerField(blank=True, null=True, verbose_name='hauteur adulte max (cm)')),
                ('width_adult_min_cm', models.IntegerField(blank=True, null=True, verbose_name='largeur adulte min (cm)')),
                ('width_adult_max_cm', models.IntegerField(blank=True, null=True, verbose_name='largeur adulte max (cm)')),
                ('growth_rate', models.CharField(blank=True, choices=[('slow', 'Lente'), ('moderate', 'Modérée'), ('fast', 'Rapide')], max_length=20, verbose_name='vitesse de croissance')),
                ('foliage', models.CharField(blank=True, choices=[('deciduous', 'Caduc'), ('evergreen', 'Persistant'), ('semi_evergreen', 'Semi-persistant')], max_length=20, verbose_name='feuillage')),
                ('flowering_months', models.JSONField(blank=True, default=list, help_text='Liste des mois de floraison (1-12)', verbose_name='mois de floraison')),
                ('flowering_color', models.CharField(blank=True, max_length=50, verbose_name='couleur floraison')),
                ('is_drought_resistant', models.BooleanField(default=False, verbose_name='résistant à la sécheresse')),
                ('frost_resistance_min_c', models.IntegerField(blank=True, null=True, verbose_name='résistance au gel min (°C)')),
                ('water_need', models.CharField(blank=True, choices=[('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé')], max_length=20, verbose_name='besoin en eau')),
                ('sun_exposure', models.CharField(blank=True, choices=[('full_sun', 'Plein soleil'), ('partial_shade', 'Mi-ombre'), ('full_shade', 'Ombre')], max_length=20, verbose_name='exposition solaire')),
                ('soil_preference', models.JSONField(blank=True, default=dict, help_text='Dictionnaire des préférences de sol', verbose_name='préférence de sol')),
                ('is_invasive', models.BooleanField(default=False, verbose_name='invasif')),
                ('attracts_pollinators', models.BooleanField(default=False, verbose_name='attire les pollinisateurs')),
                ('climate_zones', models.JSONField(blank=True, default=list, help_text='Liste des zones climatiques compatibles', verbose_name='zones climatiques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'plante',
                'verbose_name_plural': 'plantes',
            },
        ),
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fr', models.CharField(max_length=100, verbose_name='nom français')),
                ('name_latin', models.CharField(max_length=100, verbose_name='nom latin')),
            ],
            options={
                'verbose_name': 'famille de plante',
                'verbose_name_plural': 'familles de plantes',
            },
        ),
        migrations.CreateModel(
            name='PlantCareTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(help_text='Mois de 1 à 12', verbose_name='mois')),
                ('task_type', models.CharField(choices=[('watering', 'Arrosage'), ('pruning', 'Taille'), ('fertilizing', 'Fertilisation'), ('mulching', 'Paillage'), ('protection', 'Protection'), ('inspection', 'Inspection')], max_length=20, verbose_name='type de tâche')),
                ('description', models.TextField(verbose_name='description')),
                ('priority', models.CharField(choices=[('critical', 'Critique'), ('recommended', 'Recommandé'), ('optional', 'Optionnel')], default='recommended', max_length=20, verbose_name='priorité')),
                ('climate_zone', models.CharField(blank=True, max_length=50, null=True, verbose_name='zone climatique')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_templates', to='plants.plant', verbose_name='plante')),
            ],
            options={
                'verbose_name': "modèle d'entretien",
                'verbose_name_plural': "modèles d'entretien",
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='plants.plantfamily', verbose_name='famille'),
        ),
        migrations.CreateModel(
            name='PlantStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('mediterranean', 'Méditerranéen'), ('japanese', 'Japonais'), ('tropical', 'Tropical'), ('contemporary', 'Contemporain'), ('countryside', 'Champêtre')], max_length=20, verbose_name='style')),
                ('affinity_score', models.IntegerField(help_text='Score de 1 à 10', verbose_name="score d'affinité")),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_affinities', to='plants.plant', verbose_name='plante')),
            ],
            options={
                'verbose_name': 'affinité de style',
                'verbose_name_plural': 'affinités de style',
            },
        ),
        migrations.CreateModel(
            name='Plant3DModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('growth_stage', models.CharField(choices=[('young', 'Jeune'), ('intermediate', 'Intermédiaire'), ('adult', 'Adulte')], max_length=20, verbose_name='stade de croissance')),
                ('model_url', models.URLField(help_text='URL du fichier GLTF/GLB sur R2', verbose_name='URL du modèle')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL miniature')),
                ('height_in_model_cm', models.IntegerField(verbose_name='hauteur dans le modèle (cm)')),
                ('source', models.CharField(choices=[('speedtree', 'SpeedTree'), ('maxtree', 'Maxtree'), ('polyhaven', 'Poly Haven'), ('custom', 'Personnalisé')], default='custom', max_length=20, verbose_name='source')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_3d', to='plants.plant', verbose_name='plante')),
            ],
            options={
                'verbose_name': 'modèle 3D de plante',
                'verbose_name_plural': 'modèles 3D de plantes',
                'unique_together': {('plant', 'growth_stage')},
            },
        ),
        migrations.CreateModel(
            name='PlantCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('beneficial', 'Bénéfique'), ('neutral', 'Neutre'), ('incompatible', 'Incompatible')], max_length=20, verbose_name='relation')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('companion_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_of', to='plants.plant', verbose_name='plante compagnon')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='plants.plant', verbose_name='plante')),
            ],
            options={
                'verbose_name': 'association de plantes',
                'verbose_name_plural': 'associations de plantes',
                'unique_together': {('plant', 'companion_plant')},
            },
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['type'], name='plants_plan_type_a41fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['water_need'], name='plants_plan_water_n_6ee9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['sun_exposure'], name='plants_plan_sun_exp_2f4a5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantstyle',
            unique_together={('plant', 'style')},
        ),
    ]
