# Generated by Django 6.0.3 on 2026-03-16 23:53

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('role', models.CharField(choices=[('particular', 'Particulier'), ('pro', 'Professionnel'), ('agency', 'Agence'), ('admin', 'Administrateur Polsia')], default='particular', max_length=20, verbose_name='rôle')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID client Stripe')),
                ('is_verified', models.BooleanField(default=False, help_text="Indique si l'email de l'utilisateur a été vérifié.", verbose_name='email vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='logo URL')),
                ('white_label_domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='domaine marque blanche')),
                ('siren', models.CharField(blank=True, max_length=20, null=True, verbose_name='numéro SIREN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('discovery', 'Discovery'), ('particular', 'Particulier'), ('pro', 'Pro'), ('agency', 'Agence')], default='discovery', max_length=20, verbose_name='plan')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé'), ('past_due', 'En retard'), ('trialing', 'Essai')], default='trialing', max_length=20, verbose_name='statut')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID abonnement Stripe')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='début période actuelle')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='fin période actuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('member', 'Membre'), ('viewer', 'Observateur')], default='member', max_length=20, verbose_name='rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='rejoint le')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization', verbose_name='organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "membre d'organisation",
                'verbose_name_plural': "membres d'organisation",
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
