# Generated by Django 6.0.3 on 2026-03-17 00:11

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
