# Generated by Django 6.0.3 on 2026-03-16 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='budget total')),
                ('budget_tier', models.CharField(blank=True, choices=[('essential', 'Essentiel'), ('structured', 'Structuré'), ('premium', 'Premium'), ('prestige', 'Prestige')], max_length=20, null=True, verbose_name='gamme budget')),
                ('phase_plan', models.BooleanField(default=False, help_text='Si le projet doit être réalisé en plusieurs phases', verbose_name='plan par phases')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.organization', verbose_name='organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadastral_reference', models.CharField(blank=True, max_length=50, verbose_name='référence cadastrale')),
                ('geometry', models.TextField(blank=True, help_text='Contour de la parcelle en format GeoJSON (sera PostGIS en production)', null=True, verbose_name='géométrie')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='surface (m²)')),
                ('perimeter_m', models.FloatField(blank=True, null=True, verbose_name='périmètre (m)')),
                ('orientation', models.CharField(blank=True, help_text='Ex: Sud-Ouest', max_length=50, verbose_name='orientation')),
                ('raw_file_url', models.URLField(blank=True, help_text='URL du fichier PDF/DXF uploadé sur R2', verbose_name='fichier source')),
                ('source', models.CharField(choices=[('upload', 'Upload manuel'), ('ign_api', 'API IGN'), ('manual', 'Saisie manuelle')], default='upload', max_length=20, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'parcelles',
            },
        ),
        migrations.CreateModel(
            name='TerrainAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slope_percent_avg', models.FloatField(blank=True, null=True, verbose_name='pente moyenne (%)')),
                ('slope_percent_max', models.FloatField(blank=True, null=True, verbose_name='pente maximale (%)')),
                ('slope_classification', models.CharField(blank=True, choices=[('flat', 'Plat (0-2%)'), ('gentle', 'Pente douce (2-5%)'), ('moderate', 'Pente modérée (5-10%)'), ('steep', 'Pente forte (>10%)')], max_length=20, verbose_name='classification pente')),
                ('has_water_accumulation', models.BooleanField(default=False, verbose_name="accumulation d'eau")),
                ('soil_type', models.CharField(choices=[('clay', 'Argileux'), ('sandy', 'Sableux'), ('loamy', 'Limoneux'), ('chalky', 'Calcaire'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='type de sol')),
                ('soil_ph', models.FloatField(blank=True, null=True, verbose_name='pH du sol')),
                ('drainage_risk', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=20, verbose_name='risque de drainage')),
                ('mnt_file_url', models.URLField(blank=True, help_text='URL du fichier Modèle Numérique de Terrain', verbose_name='fichier MNT')),
                ('ign_data_used', models.BooleanField(default=False, verbose_name='données IGN utilisées')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='analysé le')),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terrain_analysis', to='projects.parcel', verbose_name='parcelle')),
            ],
            options={
                'verbose_name': 'analyse terrain',
                'verbose_name_plural': 'analyses terrain',
            },
        ),
        migrations.CreateModel(
            name='EarthworkRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('leveling', 'Nivellement'), ('slope_planting', 'Plantation sur pente'), ('retaining_wall', 'Mur de soutènement'), ('peripheral_drainage', 'Drainage périphérique'), ('backfill', 'Remblai'), ('excavation', 'Déblai')], max_length=30, verbose_name='type')),
                ('zone_geometry', models.TextField(blank=True, help_text='Zone concernée par la recommandation (GeoJSON)', null=True, verbose_name='zone géométrique')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='surface (m²)')),
                ('volume_m3', models.FloatField(blank=True, null=True, verbose_name='volume (m³)')),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='coût estimé min')),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='coût estimé max')),
                ('priority', models.CharField(choices=[('required', 'Obligatoire'), ('recommended', 'Recommandé'), ('optional', 'Optionnel')], default='recommended', max_length=20, verbose_name='priorité')),
                ('description', models.TextField(verbose_name='description')),
                ('terrain_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earthwork_recommendations', to='projects.terrainanalysis', verbose_name='analyse terrain')),
            ],
            options={
                'verbose_name': 'recommandation terrassement',
                'verbose_name_plural': 'recommandations terrassement',
            },
        ),
    ]
