# Generated by Django 6.0.3 on 2026-04-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='garden_style',
            field=models.CharField(blank=True, choices=[('contemporary', 'Contemporain'), ('mediterranean', 'Méditerranéen'), ('cottage', 'Cottage Anglais'), ('japanese', 'Japonais'), ('tropical', 'Tropical'), ('naturel', 'Naturel')], max_length=20, null=True, verbose_name='style de jardin'),
        ),
        migrations.AddField(
            model_name='project',
            name='maintenance_level',
            field=models.CharField(blank=True, choices=[('low', 'Faible — 1-2h/mois'), ('medium', 'Modéré — 3-5h/mois'), ('high', 'Intensif — 6h+/mois')], max_length=10, null=True, verbose_name="niveau d'entretien"),
        ),
    ]
