# Generated by Django 6.0.3 on 2026-03-18 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cache climatique',
                'verbose_name_plural': 'Caches climatiques',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='ai_climatec_latitud_9b1d10_idx'), models.Index(fields=['cached_at'], name='ai_climatec_cached__52b12c_idx')],
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='UserGenerationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generations_count_today', models.IntegerField(default=0)),
                ('generations_count_month', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('last_generation_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota de génération',
                'verbose_name_plural': 'Quotas de génération',
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_pct', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Job de génération',
                'verbose_name_plural': 'Jobs de génération',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='ai_generati_project_4319a7_idx'), models.Index(fields=['status'], name='ai_generati_status_5080bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('plan_json', models.JSONField()),
                ('context_snapshot', models.JSONField(blank=True, null=True)),
                ('prompt_snapshot', models.TextField(blank=True, null=True)),
                ('budget_json', models.JSONField(blank=True, null=True)),
                ('ai_model', models.CharField(blank=True, max_length=50, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('generation_time_s', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plans', to='projects.project')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['project', 'is_current'], name='ai_plan_project_4af9d4_idx')],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PlantCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_climatique', models.CharField(max_length=20)),
                ('zone_rusticite', models.CharField(max_length=10)),
                ('stress_hydrique', models.CharField(max_length=20)),
                ('is_compatible', models.BooleanField()),
                ('compatibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
            options={
                'verbose_name': 'Compatibilité plante',
                'verbose_name_plural': 'Compatibilités plantes',
                'indexes': [models.Index(fields=['zone_climatique', 'zone_rusticite', 'is_compatible'], name='ai_plantcom_zone_cl_8d3da0_idx'), models.Index(fields=['plant', 'is_compatible'], name='ai_plantcom_plant_i_17f6f6_idx')],
                'unique_together': {('plant', 'zone_climatique', 'zone_rusticite', 'stress_hydrique')},
            },
        ),
    ]
