# Generated by Django 6.0.3 on 2026-03-16 23:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='budget total')),
                ('budget_earthwork', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='budget terrassement')),
                ('budget_plants', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='budget végétaux')),
                ('budget_materials', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='budget matériaux')),
                ('budget_labor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="budget main d'œuvre")),
                ('budget_contingency_pct', models.FloatField(default=10.0, help_text='Pourcentage de marge pour les imprévus', verbose_name="pourcentage d'aléas")),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'plan budgétaire',
                'verbose_name_plural': 'plans budgétaires',
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('plant', 'Végétal'), ('material', 'Matériau'), ('labor', "Main d'œuvre"), ('earthwork', 'Terrassement')], max_length=20, verbose_name='catégorie')),
                ('item_code', models.CharField(max_length=50, verbose_name='code article')),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('unit', models.CharField(max_length=10, verbose_name='unité')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix min')),
                ('price_avg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix moyen')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix max')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='région')),
                ('valid_from', models.DateField(verbose_name='valide à partir du')),
                ('valid_until', models.DateField(verbose_name="valide jusqu'au")),
                ('source', models.CharField(max_length=200, verbose_name='source')),
            ],
            options={
                'verbose_name': 'prix de référence',
                'verbose_name_plural': 'prix de référence',
                'indexes': [models.Index(fields=['category', 'item_code'], name='budget_mark_categor_6688e5_idx'), models.Index(fields=['valid_from', 'valid_until'], name='budget_mark_valid_f_bf2358_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='draft', max_length=20, verbose_name='statut')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total HT')),
                ('tva_rate', models.FloatField(default=20.0, verbose_name='taux TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total TTC')),
                ('pdf_url', models.URLField(blank=True, verbose_name='URL PDF')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepté le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('plant', 'Végétal'), ('material', 'Matériau'), ('earthwork', 'Terrassement'), ('labor', "Main d'œuvre"), ('other', 'Autre')], max_length=20, verbose_name='catégorie')),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('unit', models.CharField(choices=[('unit', 'Unité'), ('m2', 'm²'), ('m3', 'm³'), ('ml', 'ml'), ('forfait', 'Forfait'), ('jour', 'Jour')], max_length=10, verbose_name='unité')),
                ('quantity', models.FloatField(verbose_name='quantité')),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire HT')),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total HT')),
                ('phase', models.IntegerField(default=1, verbose_name='phase')),
                ('design_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='designs.designelement', verbose_name='élément de design')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget.quote', verbose_name='devis')),
            ],
            options={
                'verbose_name': 'ligne de devis',
                'verbose_name_plural': 'lignes de devis',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_number', models.IntegerField(help_text='1, 2 ou 3', verbose_name='numéro de phase')),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='date de début prévue')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='date de fin prévue')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='coût estimé')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée')], default='planned', max_length=20, verbose_name='statut')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'phase de projet',
                'verbose_name_plural': 'phases de projet',
                'ordering': ['phase_number'],
                'unique_together': {('project', 'phase_number')},
            },
        ),
    ]
